openapi: 3.0.0

info:
  title: Calculator API
  description: Calculator API to perform basic operations
  version: 1.0.0

servers:
  - url: https://localhost:8080/api/v1
    description: Local server

paths:
  /calculate:
    get:
      operationId: calculate
      summary: Generic operation
      parameters:
        - in: query
          name: firstOperator
          required: true
          schema:
            type: number
        - in: query
          name: secondOperator
          required: true
          schema:
            type: number
        - in: query
          name: operation
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Operation result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OperationResponse'
        '404':
          description: Operation not found

components:
  schemas:
    OperationResponse:
      type: object
      properties:
        result:
          type: number
      required:
        - result
    Operation:
      type: string
      enum:
        - ADDITION
        - SUBTRACTION