openapi: 3.0.0

info:
  title: Calculator API
  description: Calculator API to perform basic operations
  version: 1.0.0

servers:
  - url: https://localhost:8080/api/v1
    description: Local server

paths:
  /calculate:
    get:
      operationId: calculate
      summary: Generic operation
      parameters:
        - in: query
          name: firstOperator
          required: true
          schema:
            type: number
        - in: query
          name: secondOperator
          required: true
          schema:
            type: number
        - in: query
          name: operation
          required: true
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: number
          description: Operation result
        '404':
          description: Operation not found
