/*
 * Calculator API
 * Caculator API to perform basic operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * CalculateRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-06-08T20:49:45.965+02:00[Europe/Paris]")
public class CalculateRequest {
  public static final String SERIALIZED_NAME_FIRST_OP = "firstOp";
  @SerializedName(SERIALIZED_NAME_FIRST_OP)
  private BigDecimal firstOp;

  public static final String SERIALIZED_NAME_SECOND_OP = "secondOp";
  @SerializedName(SERIALIZED_NAME_SECOND_OP)
  private BigDecimal secondOp;

  public static final String SERIALIZED_NAME_OPERATION = "operation";
  @SerializedName(SERIALIZED_NAME_OPERATION)
  private String operation;

  public CalculateRequest() {
  }

  public CalculateRequest firstOp(BigDecimal firstOp) {
    
    this.firstOp = firstOp;
    return this;
  }

   /**
   * Get firstOp
   * @return firstOp
  **/
  @javax.annotation.Nonnull
  public BigDecimal getFirstOp() {
    return firstOp;
  }


  public void setFirstOp(BigDecimal firstOp) {
    this.firstOp = firstOp;
  }


  public CalculateRequest secondOp(BigDecimal secondOp) {
    
    this.secondOp = secondOp;
    return this;
  }

   /**
   * Get secondOp
   * @return secondOp
  **/
  @javax.annotation.Nonnull
  public BigDecimal getSecondOp() {
    return secondOp;
  }


  public void setSecondOp(BigDecimal secondOp) {
    this.secondOp = secondOp;
  }


  public CalculateRequest operation(String operation) {
    
    this.operation = operation;
    return this;
  }

   /**
   * Get operation
   * @return operation
  **/
  @javax.annotation.Nonnull
  public String getOperation() {
    return operation;
  }


  public void setOperation(String operation) {
    this.operation = operation;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CalculateRequest calculateRequest = (CalculateRequest) o;
    return Objects.equals(this.firstOp, calculateRequest.firstOp) &&
        Objects.equals(this.secondOp, calculateRequest.secondOp) &&
        Objects.equals(this.operation, calculateRequest.operation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(firstOp, secondOp, operation);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CalculateRequest {\n");
    sb.append("    firstOp: ").append(toIndentedString(firstOp)).append("\n");
    sb.append("    secondOp: ").append(toIndentedString(secondOp)).append("\n");
    sb.append("    operation: ").append(toIndentedString(operation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("firstOp");
    openapiFields.add("secondOp");
    openapiFields.add("operation");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("firstOp");
    openapiRequiredFields.add("secondOp");
    openapiRequiredFields.add("operation");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to CalculateRequest
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!CalculateRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CalculateRequest is not found in the empty JSON string", CalculateRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!CalculateRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `CalculateRequest` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : CalculateRequest.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("operation").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `operation` to be a primitive type in the JSON string but got `%s`", jsonObj.get("operation").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CalculateRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CalculateRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CalculateRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CalculateRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<CalculateRequest>() {
           @Override
           public void write(JsonWriter out, CalculateRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CalculateRequest read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of CalculateRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of CalculateRequest
  * @throws IOException if the JSON string is invalid with respect to CalculateRequest
  */
  public static CalculateRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CalculateRequest.class);
  }

 /**
  * Convert an instance of CalculateRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

